apiVersion: v1
kind: Pod # El tipo de objeto a crear
metadata:
  name: pod-nginx-2
  labels:
    tipo: web
spec: # Hacemos referencia al contenedor y la imagen
  containers:
    - name: contenedor-nginx
      image: nginx:1.16
      imagePullPolicy: Always # Fuerza la descarga de la imagen
    
