version: "3.9"

# docker run --name mysql -e MYSQL_ROOT_PASSWORD=antonio  -p 3307:3306  mysql:8.0

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: antonio
      MYSQL_DATABASE: empresa3
      MYSQL_USER: antonio
      MYSQL_PASSWORD: antonio
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./empresa3_mysql.sql:/docker-entrypoint-inidb.d/empresa3_mysql.sql

   
    