version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: antonio
      MYSQL_DATABASE: empresa3
      MYSQL_USER: antonio
      MYSQL_PASSWORD: antonio
    volumes:
      - mysql-data:/var/lib/mysql
      - ./empresa3_mysql.sql:/docker-entrypoint-initdb.d/empresa3_mysql.sql
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    
  pedidos:
    image: crow5
    container_name: pedidos
    depends_on:
      - mysql
      - redis
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: antonio
      MYSQL_PASSWORD: antonio
      MYSQL_DB: empresa3
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
volumes:
  mysql-data:
  redis-data:
            
      
