services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    enviroment:
      MYSQL_ROOT_PASSWORD: antonio
      MYSQL_DATABASE: empresa3
      MYSQL_USER: antonio
      MYSQL_PASSWORD: antonio
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./empresa3_mysql.sql:/docker-entrypoint-initdb.d/empresa3_mysql.sql

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    

volumes:
  mysql_data:
  redis-data:
    
    