# Plantilla base: tomcat
FROM tomcat

# Dir de trabajo dentro del contenedor
WORKDIR /usr/local/tomcat/webapps

# Copiar el war al contenedor:
COPY aplicacion1.war .

# Exponer el puerto 8080
EXPOSE 8080