apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: practica5_crow_redis_mysql
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: antonio
            - name: MYSQL_PASSWORD
              value: antonio
            - name: MYSQL_DB
              value: empresa3
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
