services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-webs.js:/docker-entrypoint-initdb.d/init-webs.js:ro
    environment:
      MONGO_INITDB_DATABASE: bdwebs

volumes:
  mongodb_data: