# Utilizar una imagen oficial de Node.js
FROM node:alpine

# Definir el directorio de trabajo:
WORKDIR /app

# Copiar el fuente de JS a la carpeta app:
COPY mensaje.js .

# Ejecutar la aplicación
CMD ["node", "mensaje.js"]