
# Redis: dos modos (en memoria, en fichero -> AOF (Append only File)
# Modo AOF: Cada operacion de escritura se graba en un fichero: appendonly.aof
# Permite persistencia aunque se reinicie el contenedor
# Al declarar el servicio: el modo aof se indica con la etiqueta command

services:
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data: /data
    command: redis-server --appendonly yes 
    
  volumes:
    redis-data:
