// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: saludo.proto
// Protobuf C++ Version: 6.33.4

#include "saludo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace saludo {

inline constexpr Solicitud::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nombre_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Solicitud::Solicitud(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Solicitud_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SolicitudDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SolicitudDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SolicitudDefaultTypeInternal() {}
  union {
    Solicitud _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SolicitudDefaultTypeInternal _Solicitud_default_instance_;

inline constexpr Respuesta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        mensaje_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Respuesta::Respuesta(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Respuesta_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespuestaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespuestaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespuestaDefaultTypeInternal() {}
  union {
    Respuesta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespuestaDefaultTypeInternal _Respuesta_default_instance_;
}  // namespace saludo
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_saludo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_saludo_2eproto = nullptr;
const ::uint32_t
    TableStruct_saludo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::saludo::Solicitud, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::saludo::Solicitud, _impl_.nombre_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::saludo::Respuesta, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::saludo::Respuesta, _impl_.mensaje_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::saludo::Solicitud)},
        {5, sizeof(::saludo::Respuesta)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::saludo::_Solicitud_default_instance_._instance,
    &::saludo::_Respuesta_default_instance_._instance,
};
const char descriptor_table_protodef_saludo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014saludo.proto\022\006saludo\"\033\n\tSolicitud\022\016\n\006n"
    "ombre\030\001 \001(\t\"\034\n\tRespuesta\022\017\n\007mensaje\030\001 \001("
    "\t28\n\006Saludo\022.\n\006DiHola\022\021.saludo.Solicitud"
    "\032\021.saludo.Respuestab\006proto3"
};
static ::absl::once_flag descriptor_table_saludo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_saludo_2eproto = {
    false,
    false,
    147,
    descriptor_table_protodef_saludo_2eproto,
    "saludo.proto",
    &descriptor_table_saludo_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_saludo_2eproto::offsets,
    file_level_enum_descriptors_saludo_2eproto,
    file_level_service_descriptors_saludo_2eproto,
};
namespace saludo {
// ===================================================================

class Solicitud::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Solicitud>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Solicitud, _impl_._has_bits_);
};

Solicitud::Solicitud(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Solicitud_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:saludo.Solicitud)
}
PROTOBUF_NDEBUG_INLINE Solicitud::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::saludo::Solicitud& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nombre_(arena, from.nombre_) {}

Solicitud::Solicitud(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Solicitud& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Solicitud_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Solicitud* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:saludo.Solicitud)
}
PROTOBUF_NDEBUG_INLINE Solicitud::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nombre_(arena) {}

inline void Solicitud::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Solicitud::~Solicitud() {
  // @@protoc_insertion_point(destructor:saludo.Solicitud)
  SharedDtor(*this);
}
inline void Solicitud::SharedDtor(MessageLite& self) {
  Solicitud& this_ = static_cast<Solicitud&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nombre_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Solicitud::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Solicitud(arena);
}
constexpr auto Solicitud::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Solicitud),
                                            alignof(Solicitud));
}
constexpr auto Solicitud::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Solicitud_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Solicitud::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Solicitud>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Solicitud::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Solicitud>(), &Solicitud::ByteSizeLong,
              &Solicitud::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Solicitud, _impl_._cached_size_),
          false,
      },
      &Solicitud::kDescriptorMethods,
      &descriptor_table_saludo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Solicitud_class_data_ =
        Solicitud::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Solicitud::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Solicitud_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Solicitud_class_data_.tc_table);
  return Solicitud_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2>
Solicitud::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Solicitud, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Solicitud_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::saludo::Solicitud>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nombre = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Solicitud, _impl_.nombre_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nombre = 1;
    {PROTOBUF_FIELD_OFFSET(Solicitud, _impl_.nombre_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\6\0\0\0\0\0\0"
    "saludo.Solicitud"
    "nombre"
  }},
};
PROTOBUF_NOINLINE void Solicitud::Clear() {
// @@protoc_insertion_point(message_clear_start:saludo.Solicitud)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.nombre_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Solicitud::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Solicitud& this_ = static_cast<const Solicitud&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Solicitud::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Solicitud& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:saludo.Solicitud)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string nombre = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nombre().empty()) {
      const ::std::string& _s = this_._internal_nombre();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "saludo.Solicitud.nombre");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:saludo.Solicitud)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Solicitud::ByteSizeLong(const MessageLite& base) {
  const Solicitud& this_ = static_cast<const Solicitud&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Solicitud::ByteSizeLong() const {
  const Solicitud& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:saludo.Solicitud)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string nombre = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nombre().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_nombre());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Solicitud::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Solicitud*>(&to_msg);
  auto& from = static_cast<const Solicitud&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:saludo.Solicitud)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_nombre().empty()) {
      _this->_internal_set_nombre(from._internal_nombre());
    } else {
      if (_this->_impl_.nombre_.IsDefault()) {
        _this->_internal_set_nombre("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Solicitud::CopyFrom(const Solicitud& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:saludo.Solicitud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Solicitud::InternalSwap(Solicitud* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nombre_, &other->_impl_.nombre_, arena);
}

::google::protobuf::Metadata Solicitud::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Respuesta::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Respuesta>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Respuesta, _impl_._has_bits_);
};

Respuesta::Respuesta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Respuesta_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:saludo.Respuesta)
}
PROTOBUF_NDEBUG_INLINE Respuesta::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::saludo::Respuesta& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        mensaje_(arena, from.mensaje_) {}

Respuesta::Respuesta(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Respuesta& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Respuesta_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Respuesta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:saludo.Respuesta)
}
PROTOBUF_NDEBUG_INLINE Respuesta::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        mensaje_(arena) {}

inline void Respuesta::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Respuesta::~Respuesta() {
  // @@protoc_insertion_point(destructor:saludo.Respuesta)
  SharedDtor(*this);
}
inline void Respuesta::SharedDtor(MessageLite& self) {
  Respuesta& this_ = static_cast<Respuesta&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.mensaje_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Respuesta::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Respuesta(arena);
}
constexpr auto Respuesta::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Respuesta),
                                            alignof(Respuesta));
}
constexpr auto Respuesta::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Respuesta_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Respuesta::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Respuesta>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Respuesta::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Respuesta>(), &Respuesta::ByteSizeLong,
              &Respuesta::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Respuesta, _impl_._cached_size_),
          false,
      },
      &Respuesta::kDescriptorMethods,
      &descriptor_table_saludo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Respuesta_class_data_ =
        Respuesta::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Respuesta::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Respuesta_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Respuesta_class_data_.tc_table);
  return Respuesta_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2>
Respuesta::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Respuesta, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Respuesta_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::saludo::Respuesta>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string mensaje = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Respuesta, _impl_.mensaje_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string mensaje = 1;
    {PROTOBUF_FIELD_OFFSET(Respuesta, _impl_.mensaje_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\7\0\0\0\0\0\0"
    "saludo.Respuesta"
    "mensaje"
  }},
};
PROTOBUF_NOINLINE void Respuesta::Clear() {
// @@protoc_insertion_point(message_clear_start:saludo.Respuesta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.mensaje_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Respuesta::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Respuesta& this_ = static_cast<const Respuesta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Respuesta::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Respuesta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:saludo.Respuesta)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string mensaje = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_mensaje().empty()) {
      const ::std::string& _s = this_._internal_mensaje();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "saludo.Respuesta.mensaje");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:saludo.Respuesta)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Respuesta::ByteSizeLong(const MessageLite& base) {
  const Respuesta& this_ = static_cast<const Respuesta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Respuesta::ByteSizeLong() const {
  const Respuesta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:saludo.Respuesta)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string mensaje = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_mensaje().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_mensaje());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Respuesta::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Respuesta*>(&to_msg);
  auto& from = static_cast<const Respuesta&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:saludo.Respuesta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_mensaje().empty()) {
      _this->_internal_set_mensaje(from._internal_mensaje());
    } else {
      if (_this->_impl_.mensaje_.IsDefault()) {
        _this->_internal_set_mensaje("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Respuesta::CopyFrom(const Respuesta& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:saludo.Respuesta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Respuesta::InternalSwap(Respuesta* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mensaje_, &other->_impl_.mensaje_, arena);
}

::google::protobuf::Metadata Respuesta::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace saludo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_saludo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
